bin_width:
  desc: Seconds bin width
  value: 0.5
total_sequence_time:
  desc: Total sequence time in hours
  value: 2
drop_width:
  desc: Value to drop if empty (hours)
  value: 1
min_drop_count:
  desc: Minimum amount to not drop
  value: 300
sequence_length_train:
  desc: Sequence length train
  value: 1024
train_known_range
  value: [0.3,0.9]


epochs:
  desc: self-descriptive
  value: 30
batch_size:
  desc: batch size
  value: 64
lr:
  desc: learning rate
  value: 0.0005
hidden_dim:
  desc: hidden dims of GRU
  value: 2
layer_dim:
  desc: Number of stacked GRU 
  value: 2
latent_dim:
  desc: Latent dim to deal with variability in length
  value: 30
output_dim:
  desc: number of logits outputd by GRU
  value: 2
nheads:
  desc: Number of heads in the encoder of transformer
  value: 10
